### ISSUE TITLE
festo-edcon for CPX-CMAX

### ISSUE THREAD

**Issue by dani-carbonell** [Festo-se/festo-edcon#2]
Hi, 
I am trying to control a CPX-CMAX from a linux computer with Python and I came across this repo.
I am currentyl using a [CPX-CEC-C1-V3](https://www.festo.com/de/en/a/3473128/) to control it.

Is there any plans to have similar python package to control the CPX-CMAX?
If not.
What would be the best aproach to interface with if from a linux computer?

**Comment by elrosch** [comment]
Currently there are no plans for a similar package.
Most likely the best approach would be interfacing the [CPX-CEC-C1-V3](https://www.festo.com/de/en/a/3473128/) via Modbus TCP. There is a great python library for modbus access: [pymodbus](https://pymodbus.readthedocs.io/en/latest/source/readme.html)
