### ISSUE TITLE
ubuntu support

### ISSUE THREAD

**Issue by BartvanMarrewijk** [Festo-se/festo-edcon#4]
Currently, the driver only works for windows. 
Is there any guideline to get edcon working on ubuntu as well?

**Comment by elrosch** [comment]
Actually it should also work on Linux Systems.
It is even running on Raspberry Pi.
Do you have more detailed information what's not working?

**Comment by jb-chossat** [comment]
Based on my tests, the package can run for a limited amount of time on Raspberry Pi OS and arch linux. 
However, there is a bug, probably in the code managing the communication protocol (Modbus or ethernet/ip), that leads to the communication dropping. 
Anyone doing more than a few seconds of demonstration should assume it is NOT going to work on linux at this moment.

**Comment by elrosch** [comment]
Can you provide the log output when this error occurs?
Does setting the modus timeout to 0.0 in the ComModbus constructor change your behavior?

**Comment by jb-chossat** [comment]
Sure. 
No, ComModbus at 0 does not change anything in my experience. 
All data files here: 
The code run, the console output, the wireshark trace
[Modbus fail.zip](https://github.com/user-attachments/files/15974104/Modbus.fail.zip)

**Comment by elrosch** [comment]
Thanks!
I will try to get access to a Linux PC to investigate the issue.

**Comment by elrosch** [comment]
Hello,

I tried to reproduce the issue without success.
The provided script runs smoothly for > 10 min on my machine.

I also had a short look into the Wireshark traces and something worth to mention is the traffic that is happening on the ethernet interface before the connection breaks:

1. There is a MDNS cache flush (not sure what causes it nor if that is capable of breaking the TCP connection)
2. Most likely triggered by 1. there is a ICMPv6 Multicast Listener Report Message

I'd recommend you to check if this behavior is a common pattern where the connection breaks.

**Comment by RmStorm** [comment]
I've been running this overnight on a raspberry and it looks rock solid to me. I think this issue was probably something else to be honest! Also just wanna say, thank you for the amazing work you did here @elrosch.

**Comment by elrosch** [comment]
@RmStorm Thanks for that info. 
I'd close this then for now..
